version: '3'

services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    environment:
      - TZ=America/Sao_Paulo
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__MAX_THREADS=1
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      - AIRFLOW__WEBSERVER__AUTHENTICATE=False
      - AIRFLOW_LOGIN=airflow
      - AIRFLOW_PASSWORD=123
    command: ["local"]
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/home/airflow      

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    environment:
      - JUPYTER_TOKEN=123
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks